/**
 * LEGAL DISCLAIMERS - ENTERPRISE-GRADE PROFESSIONAL LANGUAGE
 *
 * Professional terminology aligned with:
 * - Australian Property Institute (API) Desktop Assessment standards
 * - CoreLogic / Landchecker industry language
 * - Automated Valuation Model (AVM) disclaimers
 * - Professional Indemnity Insurance requirements
 *
 * Purpose:
 * - Positions SimplySite as spatial engineering tool (not consumer AI app)
 * - Establishes legal firewalls under Australian regulatory frameworks
 * - Protects against misleading conduct liability (ACL Section 18)
 * - Implements "desktop assessment" professional standards
 */

/**
 * SHORT-FORM DISCLAIMER
 *
 * Usage: UI sidebar footer, dashboard footer, map overlay
 * Display: Muted grey text (text-zinc-500), small font (text-xs)
 */
export const SHORT_FORM_DISCLAIMER = `Automated Spatial Assessment Disclaimer: Figures and feasibility vectors presented are statistically derived estimates generated by an automated computational model relying on public data. This is a desktop assessment only; no physical inspection has been conducted. This data does not constitute formal architectural, legal, town planning, or valuation advice. Independent due diligence with the relevant local council and licensed professionals is strictly required prior to property acquisition or development strategy execution.`;

/**
 * FULL PROFESSIONAL INDEMNITY DISCLAIMER
 *
 * Usage: PDF export final page, comprehensive reports, legal documents
 * Display: Full-page dedicated section with proper formatting
 */
export const FULL_PROFESSIONAL_DISCLAIMER = {
  title: 'TERMS OF RELIANCE AND AUTOMATED DESKTOP ASSESSMENT EXCLUSIONS',

  sections: [
    {
      heading: '1. Nature of the Assessment',
      content: `The feasibility and yield metrics contained within this report are generated via an Automated Spatial Synthesis model. This model programmatically processes spatial geometries, local zoning schedules, and Victorian Planning Provisions (VPP) via available public data. This report constitutes a Desktop Assessment; it is executed without a physical inspection of the subject property and does not account for unrecorded physical constraints, hidden site defects, topography limits, or dynamic economic/construction market conditions.`
    },
    {
      heading: '2. Exclusion of Professional Advice',
      content: `This report must not be construed or relied upon as a professional valuation, formal architectural schematic, registered land survey, or binding town planning advice. SimplySite provides indicative feasibility vectors for preliminary screening purposes only.`
    },
    {
      heading: '3. Limitation of Liability',
      content: `To the full extent permitted by law, SimplySite (and its developers, officers, and agents) expressly excludes any warranties or representations regarding the accuracy, reliability, or completeness of the synthesized data. We accept no liability (including in negligence) for any financial loss, damage, or legal consequence arising from a user or third party's reliance on this report for property acquisition, lending, or development purposes.`
    },
    {
      heading: '4. Mandatory Data Attribution (State of Victoria)',
      content: `This assessment incorporates spatial and planning data sourced from Vicmap and the State of Victoria. The State of Victoria owns the copyright in this data. The State of Victoria does not warrant the accuracy, currency, or completeness of this data and any person using or relying upon such information does so on the basis that the State of Victoria accepts no responsibility or liability whatsoever for any errors, faults, defects, or omissions.`
    },
    {
      heading: '5. No Physical Inspection',
      content: `This desktop assessment is performed without a physical site inspection. The model does not account for: unrecorded easements, underground utilities, soil contamination, tree protection zones, slope/gradient constraints, flood inundation beyond mapped overlays, asbestos or structural defects in existing improvements, or other latent site conditions that may materially affect development feasibility.`
    },
    {
      heading: '6. Third-Party Reliance Exclusion',
      content: `This report is prepared for the named recipient only and must not be provided to financial institutions, lenders, investors, or other third parties for the purpose of securing finance, valuation, or investment decisions without SimplySite's express written consent. Third parties who obtain or rely upon this report do so entirely at their own risk.`
    }
  ],

  footer: `SimplySite Pty Ltd | Automated Desktop Assessment Platform | Report generated: ${new Date().toLocaleDateString('en-AU')} | For preliminary feasibility screening only.`
};

/**
 * VICMAP ATTRIBUTION (CC BY 4.0)
 *
 * Usage: All spatial data outputs, map displays, PDF exports
 */
export const VICMAP_ATTRIBUTION = `Spatial and cadastral data sourced from Vicmap © State of Victoria (Department of Energy, Environment and Climate Action). Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0). Data provided 'as is' for feasibility estimation only.`;

/**
 * ENTERPRISE TERMINOLOGY GUIDE
 *
 * Replace consumer AI language with professional terminology:
 */
export const TERMINOLOGY_MAP = {
  // ❌ Consumer AI Language → ✅ Professional Language
  'AI-generated': 'Automated computational model',
  'AI analysis': 'Automated spatial synthesis',
  'AI insights': 'Feasibility vectors',
  'Predicted value': 'Statistically derived estimate',
  'Guaranteed approval': 'Indicative fast-track eligibility',
  'Best use': 'Highest and best use vector',
  'Price estimate': 'Automated valuation model (AVM) estimate',
  'Site analysis': 'Desktop assessment',
  'Our analysis shows': 'The model indicates',
  'We recommend': 'Preliminary screening suggests',
};

/**
 * PROFESSIONAL REPORT CLASSIFICATION
 *
 * Usage: PDF export header, report metadata
 */
export const REPORT_CLASSIFICATION = {
  type: 'Automated Desktop Assessment',
  scope: 'Preliminary Feasibility Screening',
  method: 'Computational Spatial Synthesis',
  standard: 'Non-Compliant with API Valuation Standards (No Physical Inspection)',
  limitations: 'Desktop only - No site inspection conducted',
};
