'use client';

import React from 'react';

type FeasibilityReportProps = {
  language: 'en' | 'zh';
  address: string;
  mapSnapshot: string | null;
  zoneCode: string | null;
  zoneDescription: string | null;
  lotSize: number;
  frontage: number;
  maxYield: string;
  estValue: number;
  activeScenario: string;
  scenarioLabel: string;
  overlays: string[];
  ssdRules?: {
    maxHeight: string;
    minGarden: string;
    permitRequired: string;
  };
};

const translations = {
  en: {
    title: 'Feasibility & ROI Analysis',
    propertyAddress: 'Property Address',
    siteAnalysis: 'Site Analysis',
    zoning: 'Zoning',
    lotSize: 'Lot Size',
    frontage: 'Frontage',
    maxYield: 'Max Yield',
    estValue: 'Est. Value',
    activeScenario: 'Active Scenario',
    statutoryConstraints: 'Statutory Constraints',
    planningZone: 'Planning Zone',
    overlays: 'Overlays',
    developmentRules: 'Development Rules',
    maxHeight: 'Max Height',
    minGarden: 'Min Garden Area',
    permitRequired: 'Permit Required',
    generatedBy: 'Generated by SimplySite',
    disclaimer: 'This report is for informational purposes only. Please consult with a qualified planning professional before making development decisions.',
  },
  zh: {
    title: '可行性与投资回报分析',
    propertyAddress: '房产地址',
    siteAnalysis: '场地分析',
    zoning: '区划',
    lotSize: '占地面积',
    frontage: '临街面',
    maxYield: '最大产量',
    estValue: '预计价值',
    activeScenario: '活跃场景',
    statutoryConstraints: '法定限制',
    planningZone: '规划区',
    overlays: '叠加层',
    developmentRules: '开发规则',
    maxHeight: '最大高度',
    minGarden: '最小花园面积',
    permitRequired: '需要许可',
    generatedBy: 'SimplySite 生成',
    disclaimer: '本报告仅供参考。在做出开发决策之前，请咨询合格的规划专业人士。',
  },
};

export default function FeasibilityReportTemplate({
  language,
  address,
  mapSnapshot,
  zoneCode,
  zoneDescription,
  lotSize,
  frontage,
  maxYield,
  estValue,
  activeScenario,
  scenarioLabel,
  overlays,
  ssdRules,
}: FeasibilityReportProps) {
  const t = translations[language];

  return (
    <div
      id="pdf-report-container"
      className="absolute -left-[9999px] top-0 w-[210mm] bg-white text-black"
      style={{ fontFamily: 'Arial, sans-serif' }}
    >
      {/* Header */}
      <div className="bg-[#E9E778] p-8 flex items-center justify-between">
        <div>
          <h1 className="text-4xl font-bold tracking-widest text-[#05060E]">SIMPLYSITE</h1>
          <p className="text-sm text-[#05060E] mt-1">{t.generatedBy}</p>
        </div>
        <div className="text-right">
          <h2 className="text-xl font-bold text-[#05060E]">{t.title}</h2>
          <p className="text-xs text-[#05060E] mt-1">{new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* Property Address */}
      <div className="p-8 border-b border-gray-300">
        <p className="text-xs text-gray-600 uppercase tracking-wider mb-2">{t.propertyAddress}</p>
        <h3 className="text-2xl font-bold text-gray-900">{address || 'N/A'}</h3>
      </div>

      {/* Map Snapshot */}
      {mapSnapshot && (
        <div className="p-8 border-b border-gray-300">
          <img
            src={mapSnapshot}
            alt="Property Map"
            className="w-full h-auto rounded-lg shadow-lg"
            style={{ maxHeight: '300px', objectFit: 'cover' }}
          />
        </div>
      )}

      {/* Site Analysis Grid */}
      <div className="p-8 border-b border-gray-300">
        <h4 className="text-lg font-bold text-gray-900 mb-4">{t.siteAnalysis}</h4>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-gray-100 p-4 rounded">
            <p className="text-xs text-gray-600 uppercase tracking-wider mb-1">{t.zoning}</p>
            <p className="text-xl font-bold text-gray-900">{zoneCode || 'N/A'}</p>
          </div>
          <div className="bg-gray-100 p-4 rounded">
            <p className="text-xs text-gray-600 uppercase tracking-wider mb-1">{t.lotSize}</p>
            <p className="text-xl font-bold text-gray-900">{lotSize.toLocaleString()} m²</p>
          </div>
          <div className="bg-gray-100 p-4 rounded">
            <p className="text-xs text-gray-600 uppercase tracking-wider mb-1">{t.frontage}</p>
            <p className="text-xl font-bold text-gray-900">{frontage.toFixed(1)} m</p>
          </div>
          <div className="bg-gray-100 p-4 rounded">
            <p className="text-xs text-gray-600 uppercase tracking-wider mb-1">{t.maxYield}</p>
            <p className="text-xl font-bold text-gray-900">{maxYield}</p>
          </div>
        </div>
      </div>

      {/* Scenario Info */}
      <div className="p-8 border-b border-gray-300">
        <div className="flex justify-between items-center mb-4">
          <div>
            <p className="text-xs text-gray-600 uppercase tracking-wider mb-1">{t.activeScenario}</p>
            <p className="text-lg font-bold text-gray-900">{scenarioLabel}</p>
          </div>
          <div className="text-right">
            <p className="text-xs text-gray-600 uppercase tracking-wider mb-1">{t.estValue}</p>
            <p className="text-2xl font-bold text-green-600">
              ${(estValue / 1000000).toFixed(2)}M
            </p>
          </div>
        </div>
      </div>

      {/* Statutory Constraints */}
      <div className="p-8">
        <h4 className="text-lg font-bold text-gray-900 mb-4">{t.statutoryConstraints}</h4>

        {/* Planning Zone */}
        {zoneCode && (
          <div className="mb-4">
            <p className="text-xs text-gray-600 uppercase tracking-wider mb-2">{t.planningZone}</p>
            <div className="inline-block px-4 py-2 bg-teal-100 text-teal-800 border border-teal-300 rounded font-bold">
              {zoneCode} {zoneDescription && `- ${zoneDescription}`}
            </div>
          </div>
        )}

        {/* Overlays */}
        {overlays.length > 0 && (
          <div className="mb-4">
            <p className="text-xs text-gray-600 uppercase tracking-wider mb-2">{t.overlays}</p>
            <div className="flex flex-wrap gap-2">
              {overlays.map((overlay, idx) => (
                <div
                  key={idx}
                  className="px-4 py-2 bg-amber-100 text-amber-800 border border-amber-300 rounded font-bold text-sm"
                >
                  {overlay}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Development Rules (SSD) */}
        {ssdRules && (
          <div className="mb-4">
            <p className="text-xs text-gray-600 uppercase tracking-wider mb-2">{t.developmentRules}</p>
            <div className="bg-blue-50 border border-blue-200 rounded p-4">
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div>
                  <p className="text-gray-600 mb-1">{t.maxHeight}</p>
                  <p className="font-bold text-gray-900">{ssdRules.maxHeight}</p>
                </div>
                <div>
                  <p className="text-gray-600 mb-1">{t.minGarden}</p>
                  <p className="font-bold text-gray-900">{ssdRules.minGarden}</p>
                </div>
                <div>
                  <p className="text-gray-600 mb-1">{t.permitRequired}</p>
                  <p className="font-bold text-green-600">{ssdRules.permitRequired}</p>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Footer Disclaimer */}
      <div className="p-8 bg-gray-100 text-xs text-gray-600 text-center border-t border-gray-300">
        {t.disclaimer}
      </div>
    </div>
  );
}
